import supabase from '../database/supabase';
import { User } from '../types/user';

/**
 * Seeds the database with dummy user records
 * @returns {Promise<void>} - Resolves when the seeding operation is complete
 * @throws {Error} - If there is an error during the operation
 */
async function seedUsers() {
  const dummyUsers: Omit<User, 'id' | 'created_at' | 'updated_at'>[] = [
    {
      email: 'alice@example.com',
      password_hash: 'hashed_pw_1',
      role: 'client',
      full_name: 'Alice Johnson',
      bio: 'Client looking for creative freelancers.',
      profile_image: 'https://i.pravatar.cc/150?u=alice',
      skills: ['management', 'design'],
      hourly_rate: 0,
      subscription_plan_id: null,
    },
    {
      email: 'bob@example.com',
      password_hash: 'hashed_pw_2',
      role: 'freelancer',
      full_name: 'Bob Smith',
      bio: 'Full-stack developer passionate about web apps.',
      profile_image: 'https://i.pravatar.cc/150?u=bob',
      skills: ['javascript', 'react', 'nodejs'],
      hourly_rate: 45.5,
      subscription_plan_id: null,
    },
    {
      email: 'charlie@example.com',
      password_hash: 'hashed_pw_3',
      role: 'client',
      full_name: 'Charlie Brown',
      bio: 'Marketing specialist hiring for short projects.',
      profile_image: 'https://i.pravatar.cc/150?u=charlie',
      skills: ['marketing', 'seo'],
      hourly_rate: 0,
      subscription_plan_id: null,
    },
    {
      email: 'diana@example.com',
      password_hash: 'hashed_pw_4',
      role: 'freelancer',
      full_name: 'Diana Prince',
      bio: 'UX/UI designer with 5+ years of experience.',
      profile_image: 'https://i.pravatar.cc/150?u=diana',
      skills: ['figma', 'ux', 'ui'],
      hourly_rate: 50.0,
      subscription_plan_id: null,
    },
    {
      email: 'ethan@example.com',
      password_hash: 'hashed_pw_5',
      role: 'client',
      full_name: 'Ethan Hunt',
      bio: 'Looking for reliable web developers.',
      profile_image: 'https://i.pravatar.cc/150?u=ethan',
      skills: ['project management'],
      hourly_rate: 0,
      subscription_plan_id: null,
    },
    {
      email: 'fiona@example.com',
      password_hash: 'hashed_pw_6',
      role: 'freelancer',
      full_name: 'Fiona Gallagher',
      bio: 'Frontend engineer building modern UIs.',
      profile_image: 'https://i.pravatar.cc/150?u=fiona',
      skills: ['vue', 'tailwind', 'typescript'],
      hourly_rate: 40.0,
      subscription_plan_id: null,
    },
    {
      email: 'george@example.com',
      password_hash: 'hashed_pw_7',
      role: 'client',
      full_name: 'George Miller',
      bio: 'Startup founder building a remote team.',
      profile_image: 'https://i.pravatar.cc/150?u=george',
      skills: ['leadership', 'strategy'],
      hourly_rate: 0,
      subscription_plan_id: null,
    },
    {
      email: 'hannah@example.com',
      password_hash: 'hashed_pw_8',
      role: 'freelancer',
      full_name: 'Hannah Lee',
      bio: 'Backend developer specializing in APIs.',
      profile_image: 'https://i.pravatar.cc/150?u=hannah',
      skills: ['nodejs', 'express', 'mongodb'],
      hourly_rate: 48.0,
      subscription_plan_id: null,
    },
    {
      email: 'ian@example.com',
      password_hash: 'hashed_pw_9',
      role: 'client',
      full_name: 'Ian Curtis',
      bio: 'Looking for app developers for a new project.',
      profile_image: 'https://i.pravatar.cc/150?u=ian',
      skills: ['business', 'finance'],
      hourly_rate: 0,
      subscription_plan_id: null,
    },
    {
      email: 'jasmine@example.com',
      password_hash: 'hashed_pw_10',
      role: 'freelancer',
      full_name: 'Jasmine Flores',
      bio: 'Freelance mobile app developer.',
      profile_image: 'https://i.pravatar.cc/150?u=jasmine',
      skills: ['flutter', 'react-native'],
      hourly_rate: 60.0,
      subscription_plan_id: null,
    },
    // add 10 more for variety
    {
      email: 'kyle@example.com',
      password_hash: 'hashed_pw_11',
      role: 'client',
      full_name: 'Kyle Parker',
      bio: 'Client searching for brand designers.',
      profile_image: 'https://i.pravatar.cc/150?u=kyle',
      skills: ['branding', 'marketing'],
      hourly_rate: 0,
      subscription_plan_id: null,
    },
    {
      email: 'laura@example.com',
      password_hash: 'hashed_pw_12',
      role: 'freelancer',
      full_name: 'Laura Chen',
      bio: 'Creative graphic designer & illustrator.',
      profile_image: 'https://i.pravatar.cc/150?u=laura',
      skills: ['illustrator', 'photoshop', 'branding'],
      hourly_rate: 35.0,
      subscription_plan_id: null,
    },
    {
      email: 'michael@example.com',
      password_hash: 'hashed_pw_13',
      role: 'client',
      full_name: 'Michael Scott',
      bio: 'Hiring for web redesign projects.',
      profile_image: 'https://i.pravatar.cc/150?u=michael',
      skills: ['sales', 'communication'],
      hourly_rate: 0,
      subscription_plan_id: null,
    },
    {
      email: 'nina@example.com',
      password_hash: 'hashed_pw_14',
      role: 'freelancer',
      full_name: 'Nina Brooks',
      bio: 'Content writer for tech startups.',
      profile_image: 'https://i.pravatar.cc/150?u=nina',
      skills: ['seo', 'copywriting'],
      hourly_rate: 25.0,
      subscription_plan_id: null,
    },
    {
      email: 'oscar@example.com',
      password_hash: 'hashed_pw_15',
      role: 'client',
      full_name: 'Oscar Diaz',
      bio: 'Client in need of marketing help.',
      profile_image: 'https://i.pravatar.cc/150?u=oscar',
      skills: ['marketing'],
      hourly_rate: 0,
      subscription_plan_id: null,
    },
    {
      email: 'paula@example.com',
      password_hash: 'hashed_pw_16',
      role: 'freelancer',
      full_name: 'Paula Reyes',
      bio: 'Social media manager.',
      profile_image: 'https://i.pravatar.cc/150?u=paula',
      skills: ['social media', 'content creation'],
      hourly_rate: 30.0,
      subscription_plan_id: null,
    },
    {
      email: 'quentin@example.com',
      password_hash: 'hashed_pw_17',
      role: 'client',
      full_name: 'Quentin Blake',
      bio: 'Looking for software testers.',
      profile_image: 'https://i.pravatar.cc/150?u=quentin',
      skills: ['testing'],
      hourly_rate: 0,
      subscription_plan_id: null,
    },
    {
      email: 'riley@example.com',
      password_hash: 'hashed_pw_18',
      role: 'freelancer',
      full_name: 'Riley Adams',
      bio: 'QA engineer and automation expert.',
      profile_image: 'https://i.pravatar.cc/150?u=riley',
      skills: ['cypress', 'jest', 'selenium'],
      hourly_rate: 38.0,
      subscription_plan_id: null,
    },
    {
      email: 'samantha@example.com',
      password_hash: 'hashed_pw_19',
      role: 'client',
      full_name: 'Samantha King',
      bio: 'Business owner looking for freelancers.',
      profile_image: 'https://i.pravatar.cc/150?u=samantha',
      skills: ['entrepreneurship'],
      hourly_rate: 0,
      subscription_plan_id: null,
    },
    {
      email: 'tyler@example.com',
      password_hash: 'hashed_pw_20',
      role: 'freelancer',
      full_name: 'Tyler Grant',
      bio: 'Web designer and developer.',
      profile_image: 'https://i.pravatar.cc/150?u=tyler',
      skills: ['nextjs', 'tailwindcss', 'typescript'],
      hourly_rate: 42.0,
      subscription_plan_id: null,
    },
  ];

  const { data, error } = await supabase
    .from('Users')
    .insert(dummyUsers)
    .select();

  if (error) {
    console.error('❌ Error seeding users:', error);
  } else {
    console.log('✅ Successfully inserted users:', data.length);
  }
}

seedUsers();
